### ISSUE TITLE
SecurityException trying to open port

### ISSUE THREAD

**Issue by victorsosa** [izee/cordova-plugin-serialport#1]
Hi, 

I am getting this error trying to use this library in Ionic 3, like this:

```
  printTicket(){
    window.serialport.open('ttyS0', 9600);
  }
```

console log

```
D/dalvikvm( 1626): Added shared lib /data/app-lib/io.ionic.starter-1/libserial_port.so 0x417b0db0

D/dalvikvm( 1626): No JNI_OnLoad found in /data/app-lib/io.ionic.starter-1/libserial_port.so 0x417b0db0, skipping init
W/System.err( 1626): java.io.IOException: write failed: EPIPE (Broken pipe)
W/System.err( 1626): 	at libcore.io.IoBridge.write(IoBridge.java:455)
W/System.err( 1626): 	at java.io.FileOutputStream.write(FileOutputStream.java:187)
W/System.err( 1626): 	at java.io.OutputStream.write(OutputStream.java:82)
W/System.err( 1626): 	at android_serialport_api.SerialPort.<init>(SerialPort.java:50)
W/System.err( 1626): 	at me.izee.cordova.plugin.NativeSerial.openPort(NativeSerial.java:135)
W/System.err( 1626): 	at me.izee.cordova.plugin.NativeSerial.access$000(NativeSerial.java:24)
W/System.err( 1626): 	at me.izee.cordova.plugin.NativeSerial$1.run(NativeSerial.java:39)
W/System.err( 1626): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 1626): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 1626): 	at java.lang.Thread.run(Thread.java:841)
W/System.err( 1626): Caused by: libcore.io.ErrnoException: write failed: EPIPE (Broken pipe)
W/System.err( 1626): 	at libcore.io.Posix.writeBytes(Native Method)
W/System.err( 1626): 	at libcore.io.Posix.write(Posix.java:202)
W/System.err( 1626): 	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:197)
W/System.err( 1626): 	at libcore.io.IoBridge.write(IoBridge.java:450)
W/System.err( 1626): 	... 9 more
W/dalvikvm( 1626): threadid=24: thread exiting with uncaught exception (group=0x4163a2b8)
E/AndroidRuntime( 1626): FATAL EXCEPTION: pool-1-thread-2
E/AndroidRuntime( 1626): Process: io.ionic.starter, PID: 1626
E/AndroidRuntime( 1626): java.lang.SecurityException
E/AndroidRuntime( 1626): 	at android_serialport_api.SerialPort.<init>(SerialPort.java:57)
E/AndroidRuntime( 1626): 	at me.izee.cordova.plugin.NativeSerial.openPort(NativeSerial.java:135)
E/AndroidRuntime( 1626): 	at me.izee.cordova.plugin.NativeSerial.access$000(NativeSerial.java:24)
E/AndroidRuntime( 1626): 	at me.izee.cordova.plugin.NativeSerial$1.run(NativeSerial.java:39)
E/AndroidRuntime( 1626): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 1626): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 1626): 	at java.lang.Thread.run(Thread.java:841)
W/ActivityManager(  445):   Force finishing activity io.ionic.starter/.MainActivity
V/ActivityManager(  445): Moving to PAUSING: ActivityRecord{419f2f00 u0 io.ionic.starter/.MainActivity t7 f}
D/dalvikvm(  445): GC_FOR_ALLOC freed 529K, 20% free 6091K/7560K, paused 24ms, total 24ms

```

**Comment by victorsosa** [comment]
fixed by changing to `window.serialport.open('/dev/ttyS0', 9600);`
